In [9]:
import numpy as np

[1 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
(1, 3)


In [10]:
print(np.array([1, 2, 3]))
print(np.array([[1, 2, 3], [4, 5, 6]]))

# shape is the number of rows and columns
# 2 rows by 3 columns
print(np.array([[1, 2, 3], [4, 5, 6]]).shape)

print(np.array([[1, 2, 3]]).shape)

[1 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
(1, 3)


In [12]:
x = np.array([[1, 2, 3], [4, 5, 6]])

# 6 elements
print(x.size)

# 2d array
print(x.ndim)

# 2 rows by 3 columns
print(x.shape)

# int64
print(x.dtype)


6
2
(2, 3)
int64
