In [ ]:
# Helpful resources I used
# https://numpy.org/devdocs/user/quickstart.html
# https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d

In [2]:
import numpy as np

In [10]:
print(np.array([1, 2, 3]))
print(np.array([[1, 2, 3], [4, 5, 6]]))

# shape is the number of rows and columns
# 2 rows by 3 columns
print(np.array([[1, 2, 3], [4, 5, 6]]).shape)

print(np.array([[1, 2, 3]]).shape)

[1 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
(1, 3)


In [41]:
# ARRAY CREATION, ANALYSIS

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([
  [1, 2],
  [3, 4],
  [5, 6]
])

# 6 elements
print(x.size)

# size of individual row (2 columns)
print(f'row size: {y[0].size}')
print(f'row size - approach 2: {y.shape[1]}')

# size of individual column (3 rows)
print(f'col size: {y.shape[0]}')



6
row size: 2
row size - approach 2: 2
col size: 3


In [ ]:

# 2d array
print(x.ndim)

# 2 rows by 3 columns
print(x.shape)

# int64
print(x.dtype)

In [28]:
# CREATING A MATRIX QUICKLY

# 1x5 (row, column)
print(np.zeros(5))

# print(np.zeros(5, 2))
# 5 row by 2 column
print(np.zeros((5, 2)))

# Same works with ones
print(np.ones(5))
print(np.ones((5,2)))

# 2x3 matrix with 100s as values
print(np.full((2,3), 100))

# Identity matrix 
print (np.eye(4))

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[100 100 100]
 [100 100 100]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# Array indexing

x = np.array([[1, 2, 3], [4, 5, 6]])
print(x[0][0])
print(x[0][1])
print(x[0][2])

# Throw
print(x[0][3])


1
2
3


IndexError: index 3 is out of bounds for axis 0 with size 3

In [20]:
# Array slicing

x = np.array([
  [1, 2, 3], 
  [4, 5, 6], 
  # [7,8,9]
  ])

# row size = num columns
rowSize = x.shape[1];
numCols = rowSize
print(rowSize)

# col size = num rows
colSize = x.shape[0];
numRows = colSize
print(colSize)


# print first row
print("printing first row")
print(x[0][0:])
print(x[0][0:rowSize])
print(x[0][0:])
print(x[0, :])
      
# second row
print("printing 2nd row")
print(x[1][:])
print(x[1, :])


# print first column
print("printing first col")
# wrong: print(x[0:numRows][0])
# wrong: print(x[:][1])
# wrong: print(x[0][:])
print(x[:, 0])

# 2nd column
print("printing 2nd col")
print(x[:, 1])


3
2
printing first row
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
printing 2nd row
[4 5 6]
[4 5 6]
printing first col
[1 4]
printing 2nd col
[2 5]


In [5]:
# Vector + vector, vector - vector
# ints
print(np.array([1, 2,]) + np.array([3, 4,]))
print(np.array([1, 2,]) - np.array([3, 4,]))

# floats
print(np.array([1.1, 2.1,]) + np.array([3.1, 4.1,]))
print(np.array([1.1, 2.1,]) - np.array([3.1, 4.1,]))

[4 6]
[-2 -2]
[4.2 6.2]
[-2. -2.]


In [6]:
# Vector + scalar (broadcasting)
# ints
print(np.array([1, 2,]) + 3)
print(np.array([1, 2,]) - 3)

# floats
print(np.array([1.1, 2.1,]) + 3.1)
print(np.array([1.1, 2.1,]) - 3.1)

[4 5]
[-2 -1]
[4.2 5.2]
[-2. -1.]


In [8]:
# Vector * scalar (broadcasting)
# ints
print(np.array([1, 2,]) * 3)
print(np.array([1, 2,]) * 3)

print(np.array([1, 2,]) * 1.0)

print(np.array([1, 2,]) * 1/2)
print(np.array([1, 2,]) * 1/2)

# floats
print(np.array([1.1, 2.1,]) * 3.1)
print(np.array([1.1, 2.1,]) * 3.1)

[3 6]
[3 6]
[1. 2.]
[0.5 1. ]
[0.5 1. ]
[3.41 6.51]
[3.41 6.51]


In [13]:
# Matrix + vector (broadcasting)

# Add vector (row) to every vector (row) within the matrix
print(np.array([[1, 2,],
                [3, 4,]]) + np.array([1, 2,]))

# Out of bounds due to shape mismatch, as expected
print(np.array([[1, 2,],
                [3, 4,]]) + np.array([1, 2, 3,]))

[[2 4]
 [4 6]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [10]:
# Matrix * scalar (broadcasting, works same with + and floats)
print(np.array([[1, 2,],
                [3, 4,]]) * 3)

[[ 3  6]
 [ 9 12]]


In [17]:
# Matrix * matrix (scalar multiplication)
# Idk what the name for this operation is, element-wise multiplication?
# m3 = m1[0][0] * m2[0][0] as [0][0] value, m1[0][1]*m2[0][1] as [0][1] value, etc

m1 = np.array([[1, 2,],
                [3, 4,]])

m2 = np.array([[1, 2,],
                [1, 2,]])

print(m1*m2)

[[1 4]
 [3 8]]


In [22]:
# Matrix @ matrix (matrix multiplication / dot product)

# m3
m1 = np.array([[1, 2,],
                [3, 4,]])

m2 = np.array([[1, 2,],
                [1, 2,]])

m3 = m1@m2

# Remembered these rules by reviewing this page:
# https://www.mathsisfun.com/algebra/matrix-multiplying.html
# Dimensions rule: (m x n) @ (n x p) -> m by p, where n is the same
# m x n is m1 dimensions and n x p is m2 dimensions
# Dimensions: (2 x 2) @ (2 x 2) -> 2 x 2

# Dot product / mat mul: 
# first row of m1 dot first column of m2
# m3[0][0] = m1[0][0]*m2[0][0] + m1[0][1]*m2[1][0] + ... for all the columns of m1 (n times)
# m3[0][0] = 1*1 + 2*1 = 1 + 2 = 3
# first row of m1 dot second column of m2
# m3[0][1] = m1[0][0]*m2[0][1] + m1[0][1]*m2[1][1] + ... n times
# m3[0][1] = 1*2 + 2*2 = 2 + 4 = 6
# second row of m1 dot first column of m2
# m3[1][0] = m1[1][0]*m2[0][0] + m1[1][1]*m2[1][0] + ... n times
# m3[1][0] = 3*1 + 4*1 = 3 + 4 = 7
# second row of m1 dot second column of m2
# m3[1][1] = m1[1][0]*m2[0][1] + m1[1][1]*m2[1][1] + ... n times
# m3[1][1] = 3*2 + 4*2 = 6 + 8 = 14 
# m3[i][j] = m1[i][0]*m2[0][j] + m1[i][1]*m2[1][j] + ... n times

print("numpy matmul")
print(m3)

print("zeroing out")
m3 = np.zeros((2, 2))
print (m3)

# My own implementation of matmul based on the definition I derived above
m = m1.shape[0]
n = m1.shape[1]
for i in range(0, m):
  for j in range(0, n):
    for z in range(0, n):
      m3[i, j] += m1[i, z]*m2[z, j]

print("Tyler's matmul")
print(m3)

numpy matmul
[[ 3  6]
 [ 7 14]]
zeroing out
[[0. 0.]
 [0. 0.]]
Tyler's matmul
[[ 3.  6.]
 [ 7. 14.]]


In [ ]:
# sqrt, exp, log, power (broadcast)
# TODO:

In [ ]:
# trigonometry (broadcast)
# TODO:

In [ ]:
# rounding (broadcast), min, max
# TODO:

In [ ]:
#  sum, mean, std dev
# TODO:

In [ ]:
# Dot product
# TODO:

In [ ]:
# Cross product
# TODO:

In [ ]:
# Derivative
# TODO:

In [ ]:
# Gradient
# TODO:

In [ ]:
# Random numbers
# TODO:

In [ ]:
# Joining matrixes (hstack, vstack)
# TODO:

In [ ]:
# splitting matrixes (hsplit, vsplit)
# TODO:

In [ ]:
# Numpy arrays by referrence vs by value
# TODO: https://numpy.org/devdocs/user/quickstart.html#copies-and-views

In [ ]:
# np.append, np.insert, np.delete
# TODO:

In [ ]:
# Sorting
# TODO:

In [ ]:
# Loading/saving from/to file 
# np.loadtxt('new_file.csv')
# np.savetxt('asdf.csv')
# Actually, will use pandas for this
# TODO:

In [ ]:
# Broadcasting - cont
# TODO: https://numpy.org/devdocs/user/basics.broadcasting.html#basics-broadcasting