In [2]:
import numpy as np

In [10]:
print(np.array([1, 2, 3]))
print(np.array([[1, 2, 3], [4, 5, 6]]))

# shape is the number of rows and columns
# 2 rows by 3 columns
print(np.array([[1, 2, 3], [4, 5, 6]]).shape)

print(np.array([[1, 2, 3]]).shape)

[1 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
(1, 3)


In [41]:
# ARRAY CREATION, ANALYSIS

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([
  [1, 2],
  [3, 4],
  [5, 6]
])

# 6 elements
print(x.size)

# size of individual row (2 columns)
print(f'row size: {y[0].size}')
print(f'row size - approach 2: {y.shape[1]}')

# size of individual column (3 rows)
print(f'col size: {y.shape[0]}')



6
row size: 2
row size - approach 2: 2
col size: 3


In [ ]:

# 2d array
print(x.ndim)

# 2 rows by 3 columns
print(x.shape)

# int64
print(x.dtype)

In [17]:
# CREATING A MATRIX QUICKLY

# 1x5 (row, column)
print(np.zeros(5))

# print(np.zeros(5, 2))
# 5 row by 2 column
print(np.zeros((5, 2)))

# Same works with ones
print(np.ones(5))
print(np.ones((5,2)))

# 2x3 matrix with 100s as values
print(np.full((2,3), 100))

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[100 100 100]
 [100 100 100]]


In [19]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x[0][0])
print(x[0][1])
print(x[0][2])

# Throw
print(x[0][3])


1
2
3


IndexError: index 3 is out of bounds for axis 0 with size 3

In [20]:
x = np.array([
  [1, 2, 3], 
  [4, 5, 6], 
  # [7,8,9]
  ])

# row size = num columns
rowSize = x.shape[1];
numCols = rowSize
print(rowSize)

# col size = num rows
colSize = x.shape[0];
numRows = colSize
print(colSize)


# print first row
print("printing first row")
print(x[0][0:])
print(x[0][0:rowSize])
print(x[0][0:])
print(x[0, :])
      
# second row
print("printing 2nd row")
print(x[1][:])
print(x[1, :])


# print first column
print("printing first col")
# wrong: print(x[0:numRows][0])
# wrong: print(x[:][1])
# wrong: print(x[0][:])
print(x[:, 0])

# 2nd column
print("printing 2nd col")
print(x[:, 1])


3
2
printing first row
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
printing 2nd row
[4 5 6]
[4 5 6]
printing first col
[1 4]
printing 2nd col
[2 5]
